sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mostafamahmoud202/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mostafamahmoud202/docker-react npm run test
